### ISSUE TITLE
按流程来结果504了，什么情况

### ISSUE THREAD

**Issue by 1Dreamer666** [wibus-wee/stable_diffusion_chilloutmix_ipynb#13]
### Describe the bug

第一次和重启都504了QAQ

### Reproduction

网页连不上

### System Info

```Shell
/content/stable-diffusion-webui
Python 3.9.16 (main, Dec  7 2022, 01:11:51) 
[GCC 9.4.0]
Commit hash: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8
Installing requirements for Web UI



Launching Web UI with arguments: --share --enable-insecure-extension-access --xformers --api --cors-allow-origins * --listen
2023-03-13 12:03:53.950677: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-13 12:03:56.636753: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.9/dist-packages/cv2/../../lib64:/usr/lib64-nvidia
2023-03-13 12:03:56.636942: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.9/dist-packages/cv2/../../lib64:/usr/lib64-nvidia
2023-03-13 12:03:56.636967: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
[AddNet] Updating model hashes...
100% 9/9 [00:00<00:00, 160.05it/s]
[AddNet] Updating model hashes...
100% 9/9 [00:00<00:00, 7467.60it/s]
Loading weights [fc2511737a] from /content/stable-diffusion-webui/models/Stable-diffusion/chilloutmix_NiPrunedFp32Fix.safetensors
Creating model from config: /content/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying xformers cross attention optimization.
Error loading embedding koreanDollLikeness_v15.safetensors:
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 206, in load_from_dir
    self.load_from_file(fullfn, fn)
  File "/content/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 172, in load_from_file
    assert len(data.keys()) == 1, 'embedding file has multiple terms in it'
AssertionError: embedding file has multiple terms in it

Error loading embedding cuteGirlMix4_v10.safetensors:
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 206, in load_from_dir
    self.load_from_file(fullfn, fn)
  File "/content/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 172, in load_from_file
    assert len(data.keys()) == 1, 'embedding file has multiple terms in it'
AssertionError: embedding file has multiple terms in it

Error loading embedding fashionGirl_v45.safetensors:
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 206, in load_from_dir
    self.load_from_file(fullfn, fn)
  File "/content/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 172, in load_from_file
    assert len(data.keys()) == 1, 'embedding file has multiple terms in it'
AssertionError: embedding file has multiple terms in it

Error loading embedding yaeMikoRealistic_yaemikoMixed.safetensors:
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 206, in load_from_dir
    self.load_from_file(fullfn, fn)
  File "/content/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 172, in load_from_file
    assert len(data.keys()) == 1, 'embedding file has multiple terms in it'
AssertionError: embedding file has multiple terms in it

Error loading embedding girlsFrontlineOts14_v30.safetensors:
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 206, in load_from_dir
    self.load_from_file(fullfn, fn)
  File "/content/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 172, in load_from_file
    assert len(data.keys()) == 1, 'embedding file has multiple terms in it'
AssertionError: embedding file has multiple terms in it

Error loading embedding koreanDollLikeness_v10.safetensors:
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 206, in load_from_dir
    self.load_from_file(fullfn, fn)
  File "/content/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 172, in load_from_file
    assert len(data.keys()) == 1, 'embedding file has multiple terms in it'
AssertionError: embedding file has multiple terms in it
Textual inversion embeddings loaded(0): 
Model loaded in 13.6s (create model: 7.9s, apply weights to model: 4.4s, load textual inversion embeddings: 1.1s).
Running on local URL:  http://0.0.0.0:7860/
Running on public URL: 

This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by 1Dreamer666** [comment]
我上个月也用过老版本，没啥问题，今天想再用用发现老版本好像连不上服务器了，然后就试了一下新版本，结果还是不行

**Comment by wibus-wee** [comment]
收到！我检查下问题，谢谢～

**Comment by 1Dreamer666** [comment]
> 收到！我检查下问题，谢谢～

目前已经好了，可能是gradio的服务器出了问题
